# Generated by Django 4.1 on 2022-08-09 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenditure', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenditure',
            name='category',
            field=models.IntegerField(choices=[(1, 'food'), (2, 'health'), (3, 'home'), (4, 'transport'), (5, 'education'), (6, 'leisure'), (7, 'unforeseen'), (8, 'food')], default=8, verbose_name='category'),
        ),
    ]
